services:
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=sakila
      - MYSQL_USER=sakila
      - MYSQL_PASSWORD=sakila
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  dashboard:
    image: apache/superset
    restart: always
    volumes:
      - ./dashboard/superset.db:/app/superset_home/superset.db
    ports:
      - 8080:8088

  back:
    image: node
    working_dir: /app
    command: sh -c "npm install && npm run start"
    restart: always
    volumes:
      - ./back:/app
    ports:
      - 3000:3000

  front:
    image: node
    working_dir: /app
    command: sh -c "npm i -g --force yarn && yarn install && yarn start"
    restart: always
    volumes:
      - ./front:/app
    ports:
      - 3001:3000
